In [1]:
# import packages
import pandas as pd
import numpy as np
import os
import plotly.express as px

os.environ["PUDL_DATA_STORE"] = "s3"
os.environ["PUDL_BUILD"] = "stable"

%reload_ext autoreload
%autoreload 2

# # Tell python where to look for modules.
import sys

sys.path.append("../../src/")

import oge.download_data as download_data
import oge.load_data as load_data
from oge.column_checks import get_dtypes, apply_dtypes, DATA_COLUMNS
from oge.filepaths import *
import oge.impute_hourly_profiles as impute_hourly_profiles
import oge.data_cleaning as data_cleaning
import oge.output_data as output_data
import oge.emissions as emissions
import oge.helpers as helpers
import oge.validation as validation
import oge.gross_to_net_generation as gross_to_net_generation
import oge.eia930 as eia930
from oge.logging_util import get_logger, configure_root_logger
import oge.constants as constants

configure_root_logger()
logger = get_logger("test")


year = 2024
path_prefix = f"{year}/"

In [ ]:
# load intermediate output data as needed
cems = pd.read_csv(
    outputs_folder(f"{year}/cems_subplant_{year}.csv.zip"),
    compression="zip",
    parse_dates=["datetime_utc", "report_date"],
)
partial_cems_subplant = pd.read_csv(
    outputs_folder(f"{year}/partial_cems_subplant_{year}.csv.zip"),
    compression="zip",
    parse_dates=["datetime_utc", "report_date"],
)
partial_cems_plant = pd.read_csv(
    outputs_folder(f"{year}/partial_cems_plant_{year}.csv.zip"),
    compression="zip",
    parse_dates=["datetime_utc", "report_date"],
)
eia923_allocated = pd.read_csv(
    outputs_folder(f"{year}/eia923_allocated_{year}.csv.zip"),
    compression="zip",
    parse_dates=["report_date"],
)
plant_attributes = pd.read_csv(
    outputs_folder(f"{year}/plant_static_attributes_{year}.csv.zip"), compression="zip"
)
primary_fuel_table = pd.read_csv(
    outputs_folder(f"{year}/primary_fuel_table_{year}.csv.zip"), compression="zip"
)
monthly_eia_data_to_shape = eia923_allocated[
    (eia923_allocated["hourly_data_source"] == "eia")
]

In [2]:
# load pudl energy storage data
gens = load_data.load_pudl_table("out_eia__yearly_generators", year)

In [7]:
storage_units = gens[
    gens["technology_description"].isin(
        ["Batteries", "Flywheels", "Hydroelectric Pumped Storage"]
    )
]

In [6]:
gens[
    gens["technology_description"].isin(
        ["Natural Gas with Compressed Air Storage", "Solar Thermal with Energy Storage"]
    )
]

,plant_id_eia,generator_id,report_date,unit_id_pudl,plant_id_pudl,plant_name_eia,utility_id_eia,utility_id_pudl,utility_name_eia,balancing_authority_code_eia,balancing_authority_name_eia,technology_description,energy_source_code_1,prime_mover_code,generator_operating_date,generator_retirement_date,operational_status,capacity_mw,fuel_type_code_pudl,planned_generator_retirement_date,capacity_factor,fuel_cost_per_mmbtu_source,fuel_cost_per_mmbtu,fuel_cost_per_mwh,unit_heat_rate_mmbtu_per_mwh,net_generation_mwh,total_fuel_cost,total_mmbtu,associated_combined_heat_power,bga_source,bypass_heat_recovery,carbon_capture,city,can_cofire_fuels,county,current_planned_generator_operating_date,data_maturity,deliver_power_transgrid,distributed_generation,duct_burners,energy_source_1_transport_1,energy_source_1_transport_2,energy_source_1_transport_3,energy_source_2_transport_1,energy_source_2_transport_2,energy_source_2_transport_3,energy_source_code_2,energy_source_code_3,energy_source_code_4,energy_source_code_5,energy_source_code_6,energy_storage_capacity_mwh,ferc_qualifying_facility,fluidized_bed_tech,fuel_type_count,latitude,longitude,minimum_load_mw,can_burn_multiple_fuels,nameplate_power_factor,net_capacity_mwdc,can_switch_when_operating,operational_status_code,original_planned_generator_operating_date,other_combustion_tech,other_modifications_date,other_planned_modifications,owned_by_non_utility,ownership_code,planned_derate_date,planned_energy_source_code_1,planned_modifications,planned_net_summer_capacity_derate_mw,planned_net_summer_capacity_uprate_mw,planned_net_winter_capacity_derate_mw,planned_net_winter_capacity_uprate_mw,planned_new_capacity_mw,planned_new_prime_mover_code,planned_repower_date,planned_uprate_date,previously_canceled,pulverized_coal_tech,reactive_power_output_mvar,rto_iso_lmp_node_id,rto_iso_location_wholesale_reporting_id,solid_fuel_gasification,startup_source_code_1,startup_source_code_2,startup_source_code_3,startup_source_code_4,state,stoker_tech,street_address,subcritical_tech,summer_capacity_estimate,summer_capacity_mw,summer_estimated_capability_mw,supercritical_tech,can_switch_oil_gas,synchronized_transmission_grid,time_cold_shutdown_full_load_code,timezone,topping_bottoming_code,turbines_inverters_hydrokinetics,turbines_num,ultrasupercritical_tech,uprate_derate_completed_date,uprate_derate_during_year,winter_capacity_estimate,winter_capacity_mw,winter_estimated_capability_mw,zip_code
9766,7063,1,2024-01-01,<NA>,2688,McIntosh (AL),189,2888,PowerSouth Energy Cooperative,SOCO,"Southern Company Services, Inc. - Trans",Natural Gas with Compressed Air Storage,NG,CE,1991-06-01,NaT,existing,110.0,gas,NaT,NaN,<NA>,NaN,NaN,NaN,-1640.0,NaN,NaN,False,<NA>,False,False,McIntosh,<NA>,Washington,NaT,final,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,110.0,<NA>,<NA>,1,31.254600,-88.02990,25.0,False,0.85,NaN,<NA>,OP,NaT,<NA>,NaT,<NA>,<NA>,S,NaT,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaT,NaT,<NA>,<NA>,0.9,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,AL,<NA>,"Hwy 43, Mile 37.5",<NA>,<NA>,25.000000,NaN,<NA>,<NA>,False,1H,America/Chicago,X,<NA>,<NA>,<NA>,NaT,False,<NA>,25.000000,NaN,36553
18775,56812,GEN 1,2024-01-01,<NA>,5230,Solana Generating Station,56023,527,Arizona Solar One LLC,AZPS,Arizona Public Service Company,Solar Thermal with Energy Storage,SUN,CP,2013-10-01,NaT,existing,140.0,solar,NaT,0.336725,<NA>,NaN,NaN,NaN,414091.5,NaN,NaN,False,<NA>,False,False,Gila Bend,False,Maricopa,NaT,final,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,1,32.922294,-112.95594,NaN,False,0.90,NaN,<NA>,OP,2011-12-01,<NA>,NaT,<NA>,<NA>,S,NaT,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaT,NaT,<NA>,<NA>,NaN,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,AZ,<NA>,57750 S. Painted Rock Dam Road,<NA>,<NA>,147.800003,NaN,<NA>,<NA>,False,12H,America/Phoenix,X,<NA>,<NA>,<NA>,NaT,False,<NA>,147.800003,NaN,85337
18776,56812,GEN2,2024-01-01,<NA>,5230,Solana Generating Station,56023,527,Arizona Solar One LLC,AZPS,Arizona Public Service Company,Solar Thermal with Energy Storage,SUN,CP,2013-10-01,NaT,existing,140.0,solar,NaT,0.336725,<NA>,NaN,NaN,NaN,414091.5,NaN,NaN,False,<NA>,False,False,Gila Bend,False,Maricopa,NaT,final,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,1,32.922294,-112.95594,NaN,False,0.90,NaN,<NA>,OP,2011-12-01,<NA>,NaT,<NA>,<NA>,S,NaT,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaT,NaT,<NA>,<NA>,NaN,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,AZ,<NA>,57750 S. Painted Rock Dam Road,<NA>,<NA>,147.800003,NaN,<NA>,<NA>,False,12H,America/Phoenix,X,<NA>,<NA>,<NA>,NaT,False,<NA>,147.800003,NaN,85337
19727,57275,TSE-1,2024-01-01,<NA>,5573,Crescent Dunes Solar Energy,56641,3481,Tonopah Solar Energy LLC,NEVP,Nevada Power Company,Solar Thermal with Energy Storage,SUN,CP,2015-11-01,NaT,existing,125.0,solar,NaT,0.140621,<NA>,NaN,NaN,NaN,154402.0,NaN,NaN,False,<NA>,False,False,Tonopah,False,Nye,NaT,final,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,1,38.238889,-117.36361,NaN,False,0.90,NaN,<NA>,OP,2013-07-01,True,NaT,<NA>,<NA>,S,NaT,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaT,NaT,False,False,NaN,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,NV,<NA>,Rte 89 from the East,<NA>,<NA>,110.000000,NaN,True,<NA>,False,<NA>,America/Los_Angeles,X,<NA>,<NA>,<NA>,NaT,False,<NA>,110.000000,NaN,89049

In [4]:
list(gens["technology_description"].unique())

['Petroleum Liquids',
 'Onshore Wind Turbine',
 'Conventional Hydroelectric',
 'Natural Gas Steam Turbine',
 'Conventional Steam Coal',
 'Natural Gas Fired Combined Cycle',
 'Natural Gas Fired Combustion Turbine',
 'Nuclear',
 'Hydroelectric Pumped Storage',
 'Solar Photovoltaic',
 'Solar Thermal without Energy Storage',
 'Natural Gas Internal Combustion Engine',
 'Batteries',
 'Geothermal',
 'Municipal Solid Waste',
 <NA>,
 'Wood/Wood Waste Biomass',
 'Petroleum Coke',
 'Coal Integrated Gasification Combined Cycle',
 'Other Gases',
 'Landfill Gas',
 'Natural Gas with Compressed Air Storage',
 'All Other',
 'Other Waste Biomass',
 'Other Natural Gas',
 'Solar Thermal with Energy Storage',
 'Flywheels',
 'Offshore Wind Turbine']

In [8]:
# check that storage appears in subplant crosswalk
subplant_crosswalk = pd.read_csv(
    outputs_folder(f"{year}/subplant_crosswalk_{year}.csv.zip"), compression="zip"
)
subplant_crosswalk

       plant_id_epa emissions_unit_id_epa  plant_id_eia generator_id  subplant_id  unit_id_pudl generator_operating_date generator_retirement_date current_planned_generator_operating_date prime_mover_code  start_year  end_year
0               NaN                   NaN             1            1            1           NaN               2000-12-01                       NaN                                      NaN               IC         NaN       NaN
1               NaN                   NaN             1            2            2           NaN               2000-12-01                       NaN                                      NaN               IC         NaN       NaN
2               NaN                   NaN             1            5            3           NaN               2000-12-01                2023-02-01                                      NaN               IC         NaN       NaN
3               NaN                   NaN             1            3            4           NaN               2010-12-01                       NaN                                      NaN               IC         NaN       NaN
4               NaN                   NaN             1          WT1            5           NaN               2011-10-01                       NaN                                      NaN               WT         NaN       NaN
...             ...                   ...           ...          ...          ...           ...                      ...                       ...                                      ...              ...         ...       ...
39673           NaN                  B001        880109          NaN            1           NaN                      NaN                       NaN                                      NaN              NaN         NaN       NaN
39674           NaN                     1        880110          NaN            1           NaN                      NaN                       NaN                                      NaN              NaN         NaN       NaN
39675           NaN                     2        880110          NaN            2           NaN                      NaN                       NaN                                      NaN              NaN         NaN       NaN
39676           NaN                     3        880110          NaN            3           NaN                      NaN                       NaN                                      NaN              NaN         NaN       NaN
39677           NaN                     4        880110          NaN            4           NaN                      NaN                       NaN                                      NaN              NaN         NaN       NaN

[39678 rows x 12 columns]

In [10]:
storage_units = storage_units.merge(
    subplant_crosswalk[["plant_id_eia", "generator_id", "subplant_id"]],
    how="left",
    on=["plant_id_eia", "generator_id"],
)

In [12]:
storage_units[
    storage_units["subplant_id"].isna()
].operational_status_code.value_counts()

operational_status_code
CN    52
P     29
IP    22
L     16
T      5
U      2
Name: count, dtype: Int64