In [1]:
# import packages
import pandas as pd
import os
import zipfile

%reload_ext autoreload
%autoreload 2

# # Tell python where to look for modules.
import sys

sys.path.append("../../src")

import oge.load_data as load_data
from oge.column_checks import get_dtypes
from oge.filepaths import *


year = 2021
path_prefix = f"{year}/"

In [2]:
previous_version = "v0.7.0"

new_version_location = "local"
new_version = "v0.8.0"

s3_path = f"s3://open-grid-emissions/open_grid_emissions_data/"
local_path = "~/open_grid_emissions_data/"

previous_version_outputs_path = f"{s3_path}{previous_version}/outputs/{year}/"
previous_version_results_path = f"{s3_path}{previous_version}/results/{year}/"

if new_version_location == "s3":
    new_version_outputs_path = f"{s3_path}outputs/{year}/"
    new_version_results_path = f"{s3_path}results/{year}/"
elif new_version_location == "local":
    new_version_outputs_path = f"{local_path}outputs/{year}/"
    new_version_results_path = f"{local_path}results/{year}/"

In [ ]:
previous_plant = pd.read_csv(
    previous_version_results_path + "plant_data/annual/us_units/plant_data.csv"
)
new_plant = pd.read_csv(
    new_version_results_path + "plant_data/annual/us_units/plant_data.csv"
)

In [44]:
os.listdir((new_version_results_path + "power_sector_data/annual/us_units/CISO.csv"))

FileNotFoundError: [Errno 2] No such file or directory: '~/open_grid_emissions_data/results/2021/power_sector_data/annual/us_units/CISO.csv'

In [39]:
for ba in ["SOCO", "MISO","FPL","CISO","NEVP"]:
    previous_ef = pd.read_csv(
        previous_version_results_path + f"power_sector_data/annual/us_units/{ba}.csv"
    )
    new_ef = pd.read_csv(
        new_version_results_path + f"power_sector_data/annual/us_units/{ba}.csv"
    )
    pd.testing.assert_frame_equal(
        previous_ef.set_index("fuel_category"),
        new_ef.set_index("fuel_category"),
        rtol=0.01,
    )

In [38]:
new_ef

,fuel_category,net_generation_mwh,fuel_consumed_mmbtu,fuel_consumed_for_electricity_mmbtu,co2_mass_lb,ch4_mass_lb,n2o_mass_lb,co2e_mass_lb,nox_mass_lb,so2_mass_lb,...,generated_n2o_rate_lb_per_mwh_for_electricity,generated_co2e_rate_lb_per_mwh_for_electricity,generated_nox_rate_lb_per_mwh_for_electricity,generated_so2_rate_lb_per_mwh_for_electricity,generated_co2_rate_lb_per_mwh_for_electricity_adjusted,generated_ch4_rate_lb_per_mwh_for_electricity_adjusted,generated_n2o_rate_lb_per_mwh_for_electricity_adjusted,generated_co2e_rate_lb_per_mwh_for_electricity_adjusted,generated_nox_rate_lb_per_mwh_for_electricity_adjusted,generated_so2_rate_lb_per_mwh_for_electricity_adjusted
0,biomass,602226.0,2.425174e+07,4.782544e+06,4.752530e+09,637277.20,109240.40,4.800132e+09,7160752.20,4411063.40,...,0.0134,1222.59,7.44,1.15,187.61,0.0431,0.0125,192.21,7.13,1.14
1,coal,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
2,hydro,251607.3,2.225212e+06,2.225212e+06,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
3,natural_gas,91467861.2,6.237128e+08,6.226056e+08,7.407891e+10,1372316.01,137253.00,7.415467e+10,27861912.98,972578.80,...,0.0015,809.30,0.30,0.01,808.48,0.0150,0.0015,809.30,0.30,0.01
4,nuclear,29514894.0,3.078142e+08,3.078142e+08,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
5,other,-1538.0,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,-0.0000,-0.00,-0.00,-0.00,-0.00,-0.0000,-0.0000,-0.00,-0.00,-0.00
6,petroleum,4514.4,6.704026e+04,6.704026e+04,1.092524e+07,442.84,87.77,1.096176e+07,58111.82,14808.91,...,0.0194,2428.18,12.87,3.28,2420.09,0.0981,0.0194,2428.18,12.87,3.28
7,solar,5709714.5,5.049672e+07,5.049672e+07,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
8,total,129493437.2,1.045504e+09,1.024928e+09,8.619129e+10,4585997.65,584659.97,8.647885e+10,47542504.00,8836046.91,...,0.0037,635.44,0.34,0.04,603.43,0.0307,0.0037,605.30,0.34,0.04
9,waste,1944157.8,3.693673e+07,3.693673e+07,7.348918e+09,2575961.60,338078.80,7.513083e+09,12461727.00,3437595.80,...,0.1739,3864.44,6.41,1.77,2091.63,1.3250,0.1739,2176.07,6.41,1.77

In [36]:
previous_ef

,fuel_category,net_generation_mwh,fuel_consumed_mmbtu,fuel_consumed_for_electricity_mmbtu,co2_mass_lb,ch4_mass_lb,n2o_mass_lb,co2e_mass_lb,nox_mass_lb,so2_mass_lb,...,generated_n2o_rate_lb_per_mwh_for_electricity,generated_co2e_rate_lb_per_mwh_for_electricity,generated_nox_rate_lb_per_mwh_for_electricity,generated_so2_rate_lb_per_mwh_for_electricity,generated_co2_rate_lb_per_mwh_for_electricity_adjusted,generated_ch4_rate_lb_per_mwh_for_electricity_adjusted,generated_n2o_rate_lb_per_mwh_for_electricity_adjusted,generated_co2e_rate_lb_per_mwh_for_electricity_adjusted,generated_nox_rate_lb_per_mwh_for_electricity_adjusted,generated_so2_rate_lb_per_mwh_for_electricity_adjusted
0,biomass,602226.0,2.425174e+07,4.782544e+06,4.752530e+09,637277.20,109240.40,4.800132e+09,7160752.60,4411063.40,...,0.0134,1222.59,7.44,1.15,187.61,0.0431,0.0125,192.21,7.13,1.14
1,coal,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
2,hydro,251607.3,2.225212e+06,2.225212e+06,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
3,natural_gas,91467861.3,6.237128e+08,6.226056e+08,7.407891e+10,1372316.01,137253.00,7.415467e+10,27861913.58,972578.80,...,0.0015,809.30,0.30,0.01,808.48,0.0150,0.0015,809.30,0.30,0.01
4,nuclear,29514894.0,3.078142e+08,3.078142e+08,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
5,other,-1538.0,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,-0.0000,-0.00,-0.00,-0.00,-0.00,-0.0000,-0.0000,-0.00,-0.00,-0.00
6,petroleum,4514.4,6.704026e+04,6.704026e+04,1.092524e+07,442.84,87.77,1.096176e+07,58111.82,14808.91,...,0.0194,2428.18,12.87,3.28,2420.09,0.0981,0.0194,2428.18,12.87,3.28
7,solar,5709714.6,5.049672e+07,5.049672e+07,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.0000,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.00,0.00
8,total,129493437.4,1.045504e+09,1.024928e+09,8.619129e+10,4585997.65,584659.97,8.647885e+10,47542505.10,8836046.91,...,0.0037,635.44,0.34,0.04,603.43,0.0307,0.0037,605.30,0.34,0.04
9,waste,1944157.8,3.693673e+07,3.693673e+07,7.348918e+09,2575961.60,338078.80,7.513083e+09,12461727.10,3437595.80,...,0.1739,3864.44,6.41,1.77,2091.63,1.3250,0.1739,2176.07,6.41,1.77

In [26]:
comparison = previous_ef.set_index("fuel_category").compare(
    new_ef.set_index("fuel_category")
)

self_vals = comparison.xs("self", axis=1, level=1)
other_vals = comparison.xs("other", axis=1, level=1)
pct_diff = ((other_vals - self_vals) / self_vals * 100).round(4)
pct_diff.columns = pd.MultiIndex.from_product([pct_diff.columns, ["pct_diff"]])

comparison = pd.concat([comparison, pct_diff], axis=1).sort_index(
    axis=1, level=0, ascending=True, sort_remaining=False
)
comparison

                ch4_mass_lb                        ch4_mass_lb_adjusted  \
                       self         other pct_diff                 self
fuel_category
biomass        4.202647e+07  4.202636e+07  -0.0003         4.176049e+07
coal           2.388659e+08  2.388634e+08  -0.0010         2.388659e+08
geothermal              NaN           NaN      NaN                  NaN
hydro                   NaN           NaN      NaN                  NaN
natural_gas    2.921553e+07  2.921537e+07  -0.0005         2.921483e+07
nuclear                 NaN           NaN      NaN                  NaN
other                   NaN           NaN      NaN                  NaN
petroleum      1.826992e+06  1.826992e+06  -0.0000         1.826992e+06
solar                   NaN           NaN      NaN                  NaN
waste                   NaN           NaN      NaN                  NaN
wind                    NaN           NaN      NaN                  NaN
total          3.319425e+08  3.319397e+08  -0.0008         3.316758e+08

                                     ch4_mass_lb_for_electricity  \
                      other pct_diff                        self
fuel_category
biomass        4.176038e+07  -0.0003                1.676144e+07
coal           2.388634e+08  -0.0010                2.336204e+08
geothermal              NaN      NaN                         NaN
hydro                   NaN      NaN                         NaN
natural_gas    2.921468e+07  -0.0005                2.596572e+07
nuclear                 NaN      NaN                         NaN
other                   NaN      NaN                         NaN
petroleum      1.826992e+06  -0.0000                1.608421e+06
solar                   NaN      NaN                         NaN
waste                   NaN      NaN                         NaN
wind                    NaN      NaN                         NaN
total          3.316731e+08  -0.0008                2.954043e+08

                                     ch4_mass_lb_for_electricity_adjusted  \
                      other pct_diff                                 self
fuel_category
biomass        1.676133e+07  -0.0007                         1.650058e+07
coal           2.336179e+08  -0.0011                         2.336204e+08
geothermal              NaN      NaN                                  NaN
hydro                   NaN      NaN                                  NaN
natural_gas    2.596558e+07  -0.0006                         2.596528e+07
nuclear                 NaN      NaN                                  NaN
other                   NaN      NaN                                  NaN
petroleum      1.608421e+06  -0.0000                         1.608421e+06
solar                   NaN      NaN                                  NaN
waste                   NaN      NaN                                  NaN
wind                    NaN      NaN                                  NaN
total          2.954016e+08  -0.0009                         2.951430e+08

               ... so2_mass_lb so2_mass_lb_adjusted                         \
               ...    pct_diff                 self         other pct_diff
fuel_category  ...
biomass        ...     -0.0000         3.993597e+08  3.993597e+08  -0.0000
coal           ...     -0.0008         1.909310e+09  1.909294e+09  -0.0008
geothermal     ...         NaN                  NaN           NaN      NaN
hydro          ...         NaN                  NaN           NaN      NaN
natural_gas    ...     -0.0010         3.459266e+07  3.459232e+07  -0.0010
nuclear        ...         NaN                  NaN           NaN      NaN
other          ...         NaN                  NaN           NaN      NaN
petroleum      ...     -0.0000         2.082706e+08  2.082706e+08  -0.0000
solar          ...         NaN                  NaN           NaN      NaN
waste          ...     -0.0000         2.315748e+07  2.315748e+07  -0.0000
wind           ...         NaN                  NaN           NaN      NaN
total          ...     -0.0006         2.579886e+09  2.579870e+09  -0.0006

              so2_mass_lb_for_electricity                         \
                                     self         other pct_diff
fuel_category
biomass                      5.979084e+07  5.979082e+07  -0.0000
coal                         1.865537e+09  1.865521e+09  -0.0009
geothermal                            NaN           NaN      NaN
hydro                                 NaN           NaN      NaN
natural_gas                  2.119316e+07  2.119293e+07  -0.0011
nuclear                               NaN           NaN      NaN
other                                 NaN           NaN      NaN
petroleum                    1.173017e+08  1.173017e+08   0.0000
solar                                 NaN           NaN      NaN
waste                                 NaN           NaN      NaN
wind                                  NaN           NaN      NaN
total                        2.087591e+09  2.087575e+09  -0.0008

              so2_mass_lb_for_electricity_adjusted
                                              self         other pct_diff
fuel_category
biomass                               5.965466e+07  5.965464e+07  -0.0000
coal                                  1.865537e+09  1.865521e+09  -0.0009
geothermal                                     NaN           NaN      NaN
hydro                                          NaN           NaN      NaN
natural_gas                           2.119291e+07  2.119268e+07  -0.0011
nuclear                                        NaN           NaN      NaN
other                                          NaN           NaN      NaN
petroleum                             1.173017e+08  1.173017e+08   0.0000
solar                                          NaN           NaN      NaN
waste                                          NaN           NaN      NaN
wind                                           NaN           NaN      NaN
total                                 2.087455e+09  2.087438e+09  -0.0008

[12 rows x 90 columns]

In [12]:
test = previous_plant.compare(new_plant)

## About this notebook
This notebook can be used to identify differences between one version of OGE data and another. 
This is useful if you want to identify how much a code update affects the output results.

This notebook compares files in the `outputs` and `results` directory against archived data in the `zenodo` or `s3_upload` directories. 
This assumes that the previous, stable version of the data outputs are archived on your computer.

## Compare plant data

In [ ]:
# load archived data
data_type = "plant_data"
resolution = "annual"

# unzip archived data
if not os.path.exists(data_folder("diff")):
    os.mkdir(data_folder("diff"))
with zipfile.ZipFile(
    data_folder(f"s3_upload/{year}_{data_type}_{resolution}_us_units.zip"), "r"
) as zip_to_unzip:
    zip_to_unzip.extractall(
        data_folder(f"diff/{year}_{data_type}_{resolution}_us_units")
    )

# load archived data
prev_data = pd.read_csv(
    data_folder(f"diff/{year}_{data_type}_{resolution}_us_units/plant_data.csv"),
    dtype=get_dtypes(),
).round(0)

# load new data
new_data = pd.read_csv(
    results_folder(f"{year}/{data_type}/{resolution}/us_units/plant_data.csv"),
    dtype=get_dtypes(),
).round(0)

# load plant attributes
plant_attributes = pd.read_csv(
    outputs_folder(f"{year}/plant_static_attributes_{year}.csv"), dtype=get_dtypes()
)

prev_data = prev_data.merge(
    plant_attributes[["plant_id_eia", "ba_code", "fuel_category"]],
    how="left",
    on="plant_id_eia",
)
new_data = new_data.merge(
    plant_attributes[["plant_id_eia", "ba_code", "fuel_category"]],
    how="left",
    on="plant_id_eia",
)

key_cols = ["plant_id_eia", "ba_code", "fuel_category"]
comparison = prev_data.set_index(key_cols).compare(
    new_data.set_index(key_cols), result_names=("previous", "new")
)

# get difference
diff = (
    comparison.groupby(level=0, axis=1)
    .diff()
    .rename(columns={"new": "pct_diff"})
    .drop(columns=["previous"], level=1)
)
comparison = pd.concat([comparison, diff], axis=1).sort_index(
    axis=1, level=0, ascending=True, sort_remaining=False
)
comparison.iloc[:, comparison.columns.get_level_values(1) == "pct_diff"] = (
    comparison.iloc[:, comparison.columns.get_level_values(1) == "pct_diff"].values
    / comparison.iloc[:, comparison.columns.get_level_values(1) == "previous"].values
).round(2)

comparison

In [ ]:
comparison[
    comparison.loc[:, ("co2_mass_lb_for_electricity", "pct_diff")] > 0.001
]  # .groupby("ba_code").sum().sum()

# Compare BA data

In [ ]:
# load archived data
data_type = "power_sector_data"
resolution = "annual"

# unzip archived data
if not os.path.exists(data_folder("diff")):
    os.mkdir(data_folder("diff"))
with zipfile.ZipFile(
    data_folder(f"s3_upload/{year}_{data_type}_{resolution}_us_units.zip"), "r"
) as zip_to_unzip:
    zip_to_unzip.extractall(
        data_folder(f"diff/{year}_{data_type}_{resolution}_us_units")
    )

# load archived data
prev_data = []
for ba in os.listdir(data_folder(f"diff/{year}_{data_type}_{resolution}_us_units")):
    df = pd.read_csv(
        data_folder(f"diff/{year}_{data_type}_{resolution}_us_units/{ba}"),
        dtype=get_dtypes(),
    )
    df["ba_code"] = ba.split(".")[0]
    prev_data.append(df)

prev_data = pd.concat(prev_data, axis=0).reset_index(drop=True)

# load data
new_data = []
for ba in os.listdir(results_folder(f"{year}/{data_type}/{resolution}/us_units")):
    df = pd.read_csv(
        results_folder(f"{year}/{data_type}/{resolution}/us_units/{ba}"),
        dtype=get_dtypes(),
    )
    df["ba_code"] = ba.split(".")[0]
    new_data.append(df)

new_data = pd.concat(new_data, axis=0).reset_index(drop=True)

key_cols = ["ba_code", "fuel_category"]
comparison = prev_data.set_index(key_cols).compare(
    new_data.set_index(key_cols), result_names=("previous", "new")
)
comparison

## Compare intermediate outputs

In [ ]:
# load archived data
file = "cems_cleaned"
key_cols = ["plant_id_eia", "emissions_unit_id_epa", "datetime_utc"]

# unzip archived data
if not os.path.exists(data_folder(f"diff/outputs_{year}")):
    os.mkdir(data_folder(f"diff/outputs_{year}"))
    with zipfile.ZipFile(
        data_folder(f"zenodo/outputs_{year}.zip"), "r"
    ) as zip_to_unzip:
        zip_to_unzip.extractall(data_folder(f"diff/outputs_{year}"))

# load archived data
prev_data = pd.read_csv(
    data_folder(f"diff/outputs_{year}/{file}_{year}.csv"), dtype=get_dtypes()
)

# load new data
new_data = pd.read_csv(outputs_folder(f"{year}/{file}_{year}.csv"), dtype=get_dtypes())

comparison = prev_data.set_index(key_cols).compare(
    new_data.set_index(key_cols), result_names=("previous", "new")
)
comparison